### ISSUE TITLE
modman

### ISSUE THREAD

**Issue by tonioMtl** [DPDFrance/DPDFrance_Magento1.4-1.9#1]
Bonjour,
Merci pour votre travail.
Je voudrais ajouter l'outil modman pour automatiser l'utilisation de votre plugin.
https://github.com/colinmollenhour/modman
Voulez-vous un pull-request ?
Cordialement,

**Comment by mbrentini** [comment]
Bonjour,
Quel est l’intérêt d'utiliser modman dans le cas ou les fichiers suivent l'architecture standard de Magento ?
Cordialement

**Comment by tonioMtl** [comment]
Bonjour,
Pour moi, l'intérêt principal est l'organisation du code. Tous les fichiers d'un plugin sont rassemblés dans le même dossier. Cela permet d'avoir une vision d'ensemble immédiate de tout le plugin quand on cherche quelque chose. Cela permet aussi la gestion des plugins en ligne de commande : installation, mise à jour, désinstallation, désactivation (on garde le code mais pour magento le code n'est plus présent) ...
Aussi cela permet de facilement changer de version entre la version officielle et un fork que l'on a créé pour des tests.
Cordialement

**Comment by mbrentini** [comment]
Je saisis mieux l'intérêt de modman, merci.

Cela dit, je préfère largement garder la structure des dossiers standard pour classer les fichiers, cela permet de produire plus facilement des archives .zip pour notre site et des .tgz à destination de Magento Connect.

**Comment by tonioMtl** [comment]
Merci pour votre réponse, 
Je comprends votre point de vue. Cela ne pose pas de soucis pour le transmission des fichiers auprès de Magento Connect.
Rendre compatible un plugin avec modman consiste juste en l'ajout un fichier texte ~~modman~~ contenant la liste des fichiers du plugin avec leur chemin. Par exemple :
https://github.com/tonioMtl/MagentoCatalogCategorySearch/blob/master/modman
