### ISSUE TITLE
Conditions sur attribut non fonctionnelles

### ISSUE THREAD

**Issue by rsalmon42** [DPDFrance/DPDFrance_Magento1.4-1.9#3]
Les conditions sur les product.attribute ne fonctionnent pas dans tous les cas.

Par exemple, cette condition fonctionne sur la méthode DPD Classic mais ne fonctionne pas sur Predict et Relais 👍 

"conditions":"{cart.weight} < 300 && {count products where product.attribute.monattribut==true}==0"

J'ai l'impression qu'on ne peut utiliser ce type de condition que dans une seule méthode.

**Comment by mbrentini** [comment]
Bonjour,
	Les conditions contenant des attributs produits fonctionnent sur les 3 méthodes de livraisons.
	Par contre, chaque méthode de livraison ne peut contenir plusieurs règles ayant des « conditions » strictement similaires, auquel cas le module ne saurait quelle règle appliquer.
	Si vous utilisez des conditions vérifiant un nombre (par ex. : ….. == 0), il est possible de contourner cette limitation en utilisant < 1, <= 0.1, < 0.2…

Exemple :

{
                "Test conditions 1":
                {
                               "label": "Panier sans produit ayant condition liv_offerte vers la France",
                               "shipto": "FR-(2A,2B),MC",
                               "conditions": "{cart.weight} <= 30 && {count products where product.attribute.liv_offerte==1}<1",
                               "fees": 8.00
                },
                "Test conditions 2":
                {
                               "label": "Panier sans produits ayant condition liv_offerte vers l’Espagne",
                               "shipto": "ES ",
                               "conditions": "{cart.weight} <= 30 && {count products where product.attribute.liv_offerte==1}<=0.9",
                               "fees": 0.00
                }
}
